policy:
  approval:
    - one approval from jacksontj

approval_rules:
  - name: one approval from jacksontj
    requires:
      count: 1
      users: ["jacksontj"]
    options:
      invalidate_on_push: true
      methods:
        github_review: true
  - name: if release
    if:
      changed_files:
        paths:
          - release/.*"
    requires:
      count: 1
      users: ["jacksontj"]
    options:
      invalidate_on_push: true
      methods:
        github_review: true
