policy:
  approval:
    - or:
      - and:
        - one approval from jacksontj
        - if release
      - FORCE_COMMIT

approval_rules:
  # rule to allow for forcible commits regardless of regular review process
  - name: FORCE_COMMIT
    requires:
      count: 1
      # only some users are allowed to give this sort of commit
      teams: ["ContextLogic/core-team"]
    options:
      allow_author: true
      allow_contributor: true
      methods:
        comments:
          - FORCE_COMMIT

  # require an approval from a person/team -- using the github review process (to avoid string accidental matching)
  - name: one approval from jacksontj
    requires:
      count: 1
      users: ["jacksontj"]
    options:
      invalidate_on_push: true
      methods:
        github_review: true

  # different rule for a specific subpath
  - name: if release
    if:
      changed_files:
        paths:
          - "release/.*"
    requires:
      count: 1
      users: ["jacksontj"]
    options:
      invalidate_on_push: true
      methods:
        github_review: true
