policy:
  approval:
    - or:
      - and:
        - one approval from jacksontj
        - if release
      - FORCE_COMMIT

approval_rules:
  - name: FORCE_COMMIT
    if:
      has_author_in:
        users:
          - jacksontj
    requires:
      count: 1
    options:
      invalidate_on_push: true
      allow_author: true
      allow_contributor: true
      methods:
        comments:
          - FORCE_COMMIT
  - name: one approval from jacksontj
    requires:
      count: 1
      users: ["jacksontj"]
    options:
      invalidate_on_push: true
      methods:
        github_review: true
  - name: if release
    if:
      changed_files:
        paths:
          - "release/.*"
    requires:
      count: 1
      users: ["jacksontj"]
    options:
      invalidate_on_push: true
      methods:
        github_review: true
